### ISSUE TITLE
Does tally( y ~ x) do the right thing by default?

### ISSUE THREAD

**Issue by rpruim** [rpruim/mosaic#414]
I know that I proposed the current functionality, but I’m wondering if it is a bad idea.  Students using Chi-Squared, for example, will often send in proportions rather than counts because they are thinking about how y depends on x.  Should we have tally always produce tables of counts by default and require the user to ask for proportions?

```
> tally( substance ~ sex, data=HELPrct)
         sex
substance    female      male
  alcohol 0.3364486 0.4075145
  cocaine 0.3831776 0.3208092
  heroin  0.2803738 0.2716763
> tally( substance ~ sex, data=HELPrct, format="count")
         sex
substance female male
  alcohol     36  141
  cocaine     41  111
  heroin      30   94
```

**Comment by nicholasjhorton** [comment]
This is good, but I wonder if we need to review the vignettes to ensure that they are consistent (e.g., sometimes they give two examples to illustrate the difference from the default behavior).

Just my $0.02,

Nick

> On Dec 24, 2014, at 11:59 AM, Randall Pruim <notifications@github.com> wrote:
> 
> I've made "count" the default.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
It doesn’t look like Danny put the R output in black and white.  I’m more and more convinced that it is good this is not the final run.  I think we need to look things over more carefully than any of us has had time to do properly.

Noting like handing out 50 of them to detect problems ;-)
