### ISSUE TITLE
bug in panel.lmbands()

### ISSUE THREAD

**Issue by swang87** [rpruim/mosaic#423]
It appears that the panel.lmbands() function takes in a “level=“ argument but doesn’t actually do anything with it. The following minor fixes to lines 23-34 should do the trick:
     Clower <- function(x) {
         fit(x, interval = "confidence", level = level)[, 2]
     }
     Cupper <- function(x) {
         fit(x, interval = "confidence", level = level)[, 3]
     }
     Plower <- function(x) {
         fit(x, interval = "prediction", level = level)[, 2]
     }
     Pupper <- function(x) {
         fit(x, interval = "prediction", level = level)[, 3]
     }

**Comment by rpruim** [comment]
Thanks for finding this.  I remember now coming across this once before but forgetting to log it.  I remembered later that there was a bug, but I couldn't remember what the bug was.  Now I can fix it.

Should be fixed on github shortly.  Likely on CRAN in the next week or so.

**Comment by swang87** [comment]
Thanks, Randy! As I was mentioning to Nick, I'm learning more about mosaic each week as I use it in my Intermediate Stats class. I think it really spoils our students... in a good way!

**Comment by rpruim** [comment]
On github now (beta branch).
