### ISSUE TITLE
makeFun() issues when formula uses ~ .

### ISSUE THREAD

**Issue by swang87** [rpruim/mosaic#425]
It appears that makeFun() throws an error when we attempt to make predictions using a formula that uses a "~ ." notation. See below:

This first approach fails (with Error in eval(expr, envir, enclos) : object 'Tree' not found):

m1 <- lm(circumference ~ . , data=Orange)
pred1 <- makeFun(m1)
pred1(Tree="3", age=600)

This second one is the same model but produces proper predictions:

m2 <- lm(circumference ~ Tree + age, data=Orange)
pred2 <- makeFun(m2)
pred2(Tree="3", age=600)

**Comment by rpruim** [comment]
Fixed this by changing the definition of `modelVars()` to handle the `.` better.  The new version is based on `model$terms` rather than `model$call$formula`.

```
modelVars <- function(model) {
  all.vars(rhs(model$terms))
}

```
Here's the example above using the new code.
```
> m1 <- lm(circumference ~ ., data=Orange)
> pred1 <- makeFun(m1)
> pred1(Tree="3", age=600)
      1 
59.6047 
> pred1
function (Tree, age, ..., transform = identity) 
return(transform(predict(model, newdata = data.frame(Tree = Tree, 
    age = age), ...)))
<environment: 0x10f5d5350>
attr(,"coefficients")
(Intercept)      Tree.L      Tree.Q      Tree.C      Tree^4         age 
 17.3996502  39.9350493   2.5198917  -8.2670973  -4.6955410   0.1067703 
```
