### ISSUE TITLE
revisit statTally() in light of Hesterberg article

### ISSUE THREAD

**Issue by rpruim** [rpruim/mosaic#426]
Hesterberg seems to recommend (a) including the sample data test statistic in the distribution and (b) doubling 1-sided p-values to get 2-sided p-values.  I have to look over that section of his paper again and decide whether we want to modify `statTally()` at all based on this.

**Comment by nicholasjhorton** [comment]
This sounds eminently appropriate to me.

Nick

> On Feb 17, 2015, at 5:44 PM, Randall Pruim <notifications@github.com> wrote:
> 
> Hesterberg seems to recommend (a) including the sample data test statistic in the distribution and (b) doubling 1-sided p-values to get 2-sided p-values. I have to look over that section of his paper again and decide whether we want to modify statTally() at all based on this.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
Here's my current aproach:

```
> nullDist <- do(999) * diffmean( age ~ shuffle(sex), data=HELPrct)
Using `parallel'.  Set seed with set.rseed().
> statTally( D, nullDist)
Null distribution appears to be symmetric. (p =  0.518 )

Test statistic applied to sample data =  -0.7841

Quantiles of test statistic applied to random data:
       50%        90%        95%        99% 
0.03568149 1.11244665 1.38163795 1.88380206 

Of the 1000 samples (1 original + 999 random),

	6 ( 0.6 % ) had test stats = -0.7841

	165 ( 16.5 % ) had test stats <= -0.7841

	176 ( 17.6 % ) had test stats >= 0.8555
```
