### ISSUE TITLE
Should data frame created with do() force niced variable names?

### ISSUE THREAD

**Issue by rpruim** [rpruim/mosaic#428]
This could be implemented by passing through `data.frame()`, for example.  It would make a few things simpler for beginners, but could be very annoying if someone actually wanted to use non-nice names.  For now, users can always rename variables manually or pass things through `data.frame()` themselves.

**Comment by nicholasjhorton** [comment]
Can this be documented with an example?

Nick

> On Mar 2, 2015, at 6:15 PM, Randall Pruim <notifications@github.com> wrote:
> 
> This could be implemented by passing through data.frame(), for example. It would make a few things simpler for beginners, but could be very annoying if someone actually wanted to use non-nice names. For now, users can always rename variables manually or pass things through data.frame() themselves.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
We can easily add an example where we have 
```
sims <- do(n) * <something>
sims <- data.frame(sims)
```
Having <something> involve `predict()` seems like a reasonable example.

**Comment by rpruim** [comment]
Upon further review, I think `do()` is already doing this.  What is new is that the aggregating functions do not force nice names, but I think that is OK since generally these are used for seeing the output (or within `do()`, when the names are niced up):

```r
> favstats( cesd ~ (age > 40), data=HELPrct)
  (age > 40) min Q1 median    Q3 max     mean       sd   n missing
1      FALSE   3 25     33 40.25  60 32.62353 12.22887 340       0
2       TRUE   1 24     36 43.00  57 33.52212 13.37114 113       0
> do(3) * favstats( cesd ~ (age > 40), data=HELPrct)
Using `parallel'.  Set seed with set.rseed().
  X.age...40. min Q1 median    Q3 max     mean       sd   n missing .row .index
1       FALSE   3 25     33 40.25  60 32.62353 12.22887 340       0    1      1
2        TRUE   1 24     36 43.00  57 33.52212 13.37114 113       0    2      1
3       FALSE   3 25     33 40.25  60 32.62353 12.22887 340       0    1      2
4        TRUE   1 24     36 43.00  57 33.52212 13.37114 113       0    2      2
5       FALSE   3 25     33 40.25  60 32.62353 12.22887 340       0    1      3
6        TRUE   1 24     36 43.00  57 33.52212 13.37114 113       0    2      3
```
