### ISSUE TITLE
scoping issue in aggregation functions

### ISSUE THREAD

**Issue by homerhanumat** [rpruim/mosaic#432]
When handling formulas where one of the variables is not in the specified value of the data argument, we get unexpected results:

```
>require(mosaic)
> diff <- rnorm(32)
> favstats(diff~cyl,data=mtcars)
Error in split.default(evalF$left[, 1], joinFrames(evalF$right, evalF$condition),  : 
  first argument must be a vector
```

Similar behavior occurs in  `mosaic::t.test`, etc.

I think what happens is that when `favstats` searches for the value of "diff", it lands first on `base::diff`.  (At any rate, I've got the same issue in `tigerstats` which searches in ways similar to `mosaic`.)

Not sure it's worth trying to correct, but thought you might like to know.

Homer

**Comment by rpruim** [comment]
I'll have to do some investigating to figure out why it is finding base::diff before the `diff` you want.  This should probably be fixed, but I think the paradigm illustrated is also a bad paradigm (combining "loose" vectors with stuff in data frames.  I'd prefer something like
```
favstats(diff ~ cyl, data = mtcars %>% mutate(diff = rnorm(32))
```
I may explore using Hadley's `lazyeval` package to rewrite some of our nonstandard evaluation stuff at the same time.

**Comment by rpruim** [comment]
I think I have this fixed.
```
> require(mosaic)
> diff <- rnorm(32)
> favstats(diff~cyl, data=mtcars)
  .group        min         Q1     median        Q3      max       mean        sd  n missing
1      4 -2.2331442 -0.7645801  0.7246650 0.8058185 2.532752  0.1614522 1.3212377 11       0
2      6 -2.1087798 -1.5549843 -0.7992673 0.4773888 2.456459 -0.3723970 1.6061211  7       0
3      8 -0.9752573 -0.1812960  0.6183077 1.0440287 1.181276  0.3858517 0.7675842 14       0
```

In several places we have argument defaults like `data = parent.frame()` but to be able to look in both a data set and an environment (when an object is not found in the data frame), we need to also pass around enclosing environments.  When functions get nested, using the default of `enclos=parent.frame()` when `env` is a data frame doesn't work because by the time `eval()` is called, the desired environment is no longer `parent.frame()`.

**Comment by rpruim** [comment]
It turned out to be easier to fix this without using `lazyeval` given the current starting point, but the idea behind the fix is very similar to the design of `lazyeval`.
