### ISSUE TITLE
improve error message for augmented t.test()

### ISSUE THREAD

**Issue by nicholasjhorton** [rpruim/mosaic#433]
Standard t.test() function gives error about exactly 2 levels (but the error is not nearly as clear for augmented mosaic function).  Kudos to Dick DeVeaux for the report.

Nick

> x <- c("M", "M", "F", "F", " ")
> y <- c(1, 2, 3, 5, 7)
> df <- data.frame(x, y); rm (x, y)
> with(df, t.test(y ~ x))
Error in t.test.formula(y ~ x) : 
  grouping factor must have exactly 2 levels
> require(mosaic)
> t.test(y ~ x, data=df)
Error in if (stderr < 10 * .Machine$double.eps * abs(mx)) stop("data are essentially constant") : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In mean.default(x) : argument is not numeric or logical: returning NA

**Comment by rpruim** [comment]
We can easily fix this as a one-off:
```
> library(mosaic)
> t.test( age ~ substance, data=HELPrct)
Error in t.test.formula(x, data = data, ...) : 
  grouping factor must have exactly 2 levels
```
But there may be similar sorts of situations that remain.  I don't know a good way to determine all of the errors that `stats::t.test()` might throw so we could decide which of these to forward on and which to ignore before using the `mosaic` version.   We could use either an opt-in or opt-out strategy.

For now, I'm just handling this one type of error separately (and passing the error along).
