### ISSUE TITLE
Vignette housecleaning

### ISSUE THREAD

**Issue by rpruim** [rpruim/mosaic#438]
We have talked about some of this before.  Here is my proposal:

## 1. Reduce the number of official vignettes in the package

This will make the package a bit smaller and make it easier to have vignette-like things updated on a cycle that might not exactly match the CRAN pushes of the package.

## 2. As much as possible, include only vignettes that compile in the usual vignette way

That would mean that they would be compiled each time the package is built (ensuring that things work and that the vignette is up to date) and avoid all of our work-arounds currently in place.

## 3. Move external vignette repositories to the ProjectMOSAIC organization

This would reduce the amount of confusion over where these things are, which are most recent, etc.  It would also help seed the ProjectMOSAIC organization with some content.

## 4. Perhaps (eventually) write some additional vignettes

The idea would be to include things that can be created using the standard mechanism (without taking too long -- need to be careful about the use of `do()`, for example) and would be useful for people getting started with the package.

## 5. Perhaps keep a vignette like the mosaic resources vignette that points to the location of "off site" resources 

Most of these will, I hope, be housed at ProjectMOSAIC.  Perhaps this could be really short and basically just provide a link to an index/table of contents located at ProjectMOSAIC.  Perhaps this continues to look like the current mosaic resources vignette.

## 6. Make some decisions about which current vignettes stay as vignettes in the package

I'm thinking that Minimal R stays, the "little books" leave (because they are big and don't compile nicely in the usual vignette way.  Perhaps Less Volume/More Creativity stays, but it isn't quite compliant either, IIRC.  Is there anything else important to keep inside the package?

**Comment by znmeb** [comment]
IMHO as long as everything builds it should stay in the package. I really don't like to go copy-and-paste links from RStudio's browser into my main browser, or worse, have to invoke a search engine to find a document/article/paper/vignette. Of course I'm running RStudio 0.99.xxx, the preview release - I suspect it would be even worse with 0.98.xxx.

**Comment by rpruim** [comment]
I have converted the Less Volume vignette from an Rpres to an Rmd file and modified it so that it makes a better vignette.  (I've added some text to reflect things that would be said when presenting the slides and reformatted for a scrolling page view rather than a slides view.)

**Comment by rpruim** [comment]
CRAN is not particularly happy with the size of the mosaic package.  We have already been asked to remove the data sets (now in `mosaicData`).  A lot of the size comes from the large vignettes, which can't be effectively compiled inside the package the vignettes are "meant" to be. There are workflow issues for us as well that might be simplified by putting these longer documents elsewhere.

**Comment by rpruim** [comment]
Regarding items 2 and 6 above:
 
 * I've converted Less Volume into a more traditional vignette.  
 * I believe that mosaicresources is already good to go
 * Next up: checking whether it is easy to move Minimal R to a standard vignette format.
 * For now, I've moved the other vignettes out.  (They are stashed away in sandbox/Vignettes, so they are easy to bring back if we want them.)

**Comment by rpruim** [comment]
Vignetteable version of Minimal R -- check.  Along the way I've removed as many latex package dependencies as I could.  In particular, I've moved some definitions from my `language.sty` into this file so that it does not depend on that.

**Comment by rpruim** [comment]
Current status of vignettes in the package:
![image](https://cloud.githubusercontent.com/assets/722231/7507868/ebb91db0-f4ca-11e4-998a-0b497299d0e2.png)

HTML, PDF, and R files are being auto-generated.  `R.rsp` has been removed as a dependency since we are no longer using the "as.is" hack.

**Comment by znmeb** [comment]
> CRAN is not particularly happy with the size of the mosaic package. We have already been asked to remove the data sets (now in mosaicData). A lot of the size comes from the large vignettes, which can't be effectively compiled inside the package the vignettes are "meant" to be. There are workflow issues for us as well that might be simplified by putting these longer documents elsewhere.

Perhaps a third package then? mosaic, mosaicData and mosaicDocs?

**Comment by rpruim** [comment]
Resampling vignette is now in place:
![image](https://cloud.githubusercontent.com/assets/722231/7510632/72321abe-f4f2-11e4-9da2-4c2a62f1b9ae.png)

**Comment by rpruim** [comment]
I think the main work here is done.  We can open issues for little things that need fixing.
